version: "3"

# ==============================================================================
# MONACO CLIENT - TASKFILE (v1.2 - Angular 21 + Docker)
# ==============================================================================

vars:
    PROJECT_NAME: monaco-client
    DOCKER_DEV_COMPOSE: docker compose -f docker-compose.yml -f docker-compose.override.yml
    DOCKER_PROD_COMPOSE: docker compose -f docker-compose.yml

tasks:
    # --- AMBIENTE LOCAL ---

    install:
        desc: "Executa npm install padrão"
        cmds:
          - docker compose run --rm monaco-client npm install
          - task: fix-permissions
        sources:
          - package.json
        generates:
          - node_modules/**/*

    ng:install:
        desc: "Instala um pacote específico (uso: task ng:install pkg=nome-do-pacote)"
        cmds:
          - 'docker compose run --rm monaco-client npm install {{.pkg}}'
          - task: fix-permissions
        preconditions:
          - sh: '[ -n "{{.pkg}}" ]'
            msg: "ERRO: Você precisa passar o pacote. Ex: task ng:install pkg=lodash"

    dev:
        desc: "Sobe o ambiente LOCAL com Hot Reload"
        deps: [ install ]
        cmds:
          - "{{.DOCKER_DEV_COMPOSE}} up -d"
          - echo "✔ SisMônaco Frontend pronto em http://localhost:4200"

    # --- QUALIDADE ---

    lint:
        desc: "Executa a checagem de linting no projeto"
        cmds:
          - docker compose run --rm monaco-client npm run lint

    # --- PRODUÇÃO ---

    prod:build:
        desc: "Gera imagem de PRODUÇÃO"
        cmds:
          - docker build -t {{.PROJECT_NAME}}:latest -f Dockerfile .

    prod:up:
        desc: "Sobe container de PRODUÇÃO (Nginx)"
        cmds:
          - "{{.DOCKER_PROD_COMPOSE}} up -d"

    # --- UTILITÁRIOS ---

    fix-permissions:
        desc: "Corrige permissões de arquivos (Root -> User)"
        cmds:
          - sudo chown -R $USER:$USER .
        silent: true

    down:
        desc: "Para todos os containers"
        cmds:
          - docker compose down --remove-orphans

    shell:
        desc: "Shell dentro do container Node"
        cmds:
          - docker compose run --rm monaco-client sh
